spring:
  application:
    name: user-service

  mvc:
    problemdetails:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/miniwallet?currentSchema=user_service
    username: wallet
    password: wallet

  flyway:
    schemas:
      - user_service
    locations:
      - classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

app:
  jwt:
    issuer: mini-wallet-user-service
    access-token-ttl: 15m
    private-key: classpath:keys/jwt-private.pem
    public-key: classpath:keys/jwt-public.pem

server:
  port: 8084
