spring:
  application:
    name: ledger-service

  mvc:
    problemdetails:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/miniwallet?currentSchema=ledger
    username: wallet
    password: wallet

  flyway:
    schemas:
      - ledger
    locations:
      - classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8081

app:
  jwt:
    issuer: mini-wallet-user-service
    public-key: classpath:keys/jwt-public.pem
